config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root  'items#index'
  resources :items do
    resources :purchases, only:[:index, :create]
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    だれでもかんたん、人生を変えるフリマアプリ
  </p>
  <h2 class='ad-footer-title'>
    今すぐ無料ダウンロード！
  </h2>
  <div class='store-btn'>
    <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "https://www.apple.com/jp/ios/app-store/" %>
    <%= link_to image_tag("dl-android.png", class:"google-btn"), "https://play.google.com/store" %>
  </div>
</div>


<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMA利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
        <li><%= link_to 'ブランド一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to 'FURIMAガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMAロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("furima-logo-white.png", class:"logo-white"), "#" %>
  <p>© FURIMA</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("furima-logo-color.png", class:"furima-icon"), "/" %>
    <%= form_with(url: search_items_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "キーワードから探す", class: "input-box" %>
      <%= button_tag type: "submit", class: "search-button" do %>
        <%= image_tag "search.png", class:"search-icon" %>
      <% end %>
    <% end %>  
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to 'カテゴリー', "#", class: "category-list" %></li>
      <li><%= link_to 'ブランド', "#", class: "brand-list" %></li>
    </ul>
    <ul class='lists-right'>
      <% if user_signed_in?%>
        <li><%= link_to current_user.nickname, "#", class: "user-nickname" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>

    </ul>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>FURIMA利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <%= image_tag "furima-logo-color.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("furima-logo-color.png", class:"second-logo"), "/" %>
</header>